### ISSUE TITLE
Money being duplicated for no rhyme or reason & other issues

### ISSUE THREAD

**Issue by RSNFreud** [iconomy5legacy/iConomy#13]
Ever since installing your plugin people's accounts are being duplicated without them doing anything. There is nothing in the logs that I can see that could be causing it.

Latest Log: https://pastebin.com/mp2QhzvZ
Config: https://pastebin.com/7GZAyVe4
Version: iConomy-5.10-SNAPSHOT

**Comment by RSNFreud** [comment]
To add to this offline players show as not having an account and /money top sometimes works and sometimes doesnt

**Comment by ElgarL** [comment]
I'm not seeing these issues. I just tested "money top" and it works fine every time for me.
I also tested an offline player and it works every time as well.

You'll need to explain what you mean by accounts being duplicated. I'm seeing no issues with any accounts.

**Comment by RSNFreud** [comment]
People start with their normal cash balance and at random it doubles and triples. Would you like to take a look on the server itself?

**Comment by AAigars** [comment]
I had this problem too when I compiled the master branch, it seems to happen once a player pays someone money, their balance is then duplicated.

**Comment by LlmDl** [comment]
This was solved for @AAigars you'll want to re-build from master again.
