### ISSUE TITLE
[Question] Is there a way to convert from h2 to mysql?

### ISSUE THREAD

**Issue by ryan-bing** [iconomy5legacy/iConomy#15]
Is there a way to convert from h2 to mysql? I am opening another server, and would like to link the economies. I cannot do this with h2, and can't figure out a way to convert to mysql to allow for a connected economy.

Also, I saw that it says Towny is required to use this plugin. Is it *really* required, or will I be fine without it? Right now it's running on a Towny server, but I am opening a second server that is Factions. Would I be fine installing iConomy on the Factions server and linking it via mysql?

EDIT:
I just looked into this a bit more. Theoretically, could I do the following:
1. Use /baltop to sync iConomy to essentials eco.
2. Stop the server and convert iConomy to mysql
3. Start the server and import the economy from essentials back to iConomy

Would there be any risk here to my existing data?

**Comment by LlmDl** [comment]
Towny is the only thing that makes this plugin handle name changes, so towny is required.

Your idea on how to convert will probably be ok.

**Comment by ryan-bing** [comment]
Got it. Any other common Towny economy plugins (that aren't just for Towny) that you recommend? I really liked iConomy because of how simple it was (i.e. if it weren't for the essentials economy bug, I would be using that).

**Comment by LlmDl** [comment]
Just about anything will work, except EssEco and I think aConomy.
