### ISSUE TITLE
Possible server crash because of iConomy using MySQL?

### ISSUE THREAD

**Issue by Agaloth** [iconomy5legacy/iConomy#19]
https://pastebin.com/fBzbpRKx

**Server and plugin information:**
Server version: 1.16.5 git-Purpur-1050
Plugin version: iConomy version 5.11

**How to reproduce it:**
Have an 12000+ essentials data files with various people having eco on them, use MySQL then run the server until a freeze/crash happens.

**Comment by ElgarL** [comment]
The number of accounts in essentials will have zero effect on iConomy.
From your crash it looks like your MySQL server failed to respond for over 10 seconds.

**Comment by Agaloth** [comment]
Hmm, I'll check that more in detail with my host and keep you updated!

**Comment by LlmDl** [comment]
Hey its the guy that wanted to bring down Towny via some sketchy copyright issue.

**Comment by MWHunter** [comment]
Is closing this ticket and blocking Agaloth an in-season April fool's joke?

**Comment by LlmDl** [comment]
No, Agaloth is persona non grata to me.
