### ISSUE TITLE
iConomy doesn't work in 1.14 because of async event change.

### ISSUE THREAD

**Issue by xSorch** [iconomy5legacy/iConomy#8]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

What steps will reproduce the problem?
Unable to /plot claim in order to claim a plot.
What is the expected output?
Error
What is your Towny version?
Do not say "latest".
https://gyazo.com/b123562f033d1afa0bf4be4281df8820

What is your spigot/craftbukkit version?
Do not say "latest".
https://gyazo.com/d1df565f86d8998c0d8832d8bc5e23c5

Please use Pastebin.com to link the following files:
Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

Your full server startup from the logs\latest.log : https://pastebin.com/PpK4SkAQ
Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/YgZNd5j5
Your townyperms.yml : https://pastebin.com/canLU4dJ
Your log's error : https://pastebin.com/YgZNd5j5
(optional) If this is to do with permissions,
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your link to the error is just a second link to your config.

**Comment by xSorch** [comment]
> Your link to the error is just a second link to your config.

My bad, here https://pastebin.com/j6eRstXR

**Comment by graywolf336** [comment]
I'll take a look at this tomorrow 👍

**Comment by PantallazoAzul** [comment]
Same error :(

**Comment by Momshroom** [comment]
I'd love to see this working

**Comment by LlmDl** [comment]
Anyone wanting to test this out, let me know if I missed anything for 1.14 compatibility:
https://cdn.discordapp.com/attachments/581163022874050569/618228648939487232/iConomy-5.09.jar

**Comment by Momshroom** [comment]
I'll load the new on in momentarily, but I think this is the only one I've seen in my current log with the PRIOR version is:
https://pastebin.com/cksHSeqn

**Comment by LlmDl** [comment]
Fixed as far as I can tell: get the jar here: https://github.com/iconomy5legacy/iConomy/releases/tag/v5.9
